version: "3"
services:
  node:
    image: node:12.16
    user: "node"
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    depends_on: 
      - db
    # volumes:
    #   - ./node:/home/node/app
    expose:
      - "8888"
    command: bash -c
      "npm install
      && npm start"
  db:
    image: postgres:12.2
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - ./pgdata:/home/postgres/postgresql/data
    ports: 
      - '5432:5432'
    expose: 
      - "5432"