version: "3"
services:
  node:
    image: node:13.8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/.:/home/node/app
    expose:
      - "8888"
    command: "npm start"
  db:
    image: postgres:12.2
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on: 
      - node
    volumes: 
      - ./pgdata:/home/postgres/postgresql/data
    ports: 
      - '5432:5432'